// Investigation data — distilled from case studies in the repo.
// Sources: Tempo, ICW, BBC, Kompas, CNN Indonesia, AHU Online, LPSE, BPK audits.
window.INVESTIGATION_DATA = {
  stats: {
    entities: 51,
    relations: 57,
    redFlags: 26,
    sppg: 26103,
    budget: "Rp 335 T",
    yayasanParpol: 28,
    lastUpdate: "2026-04-12",
  },

  dossiers: [
    {
      id: "mbg",
      code: "DOSSIER / 01",
      status: "CRITICAL",
      title: "Makan Bergizi Gratis",
      subtitle: "Krisis Konstitusi & Anggaran Rp 335 Triliun",
      kicker: "Anggaran flagship dipertanyakan Mahkamah Konstitusi. 28 yayasan mitra terafiliasi partai. Staf internal BGN mendirikan yayasan penerima kontrak.",
      budget: "Rp 335 T",
      budgetNote: "Anggaran 2026 — naik dari Rp 71 T (2025)",
      entities: 28,
      redFlags: 12,
      severity: "HIGH",
      sources: "MK-RI · ICW · Tempo · BBC Indonesia",
      keyFacts: [
        { label: "Anggaran 2026", value: "Rp 335 T", note: "Dana pendidikan Rp 223,55 T digugat di MK" },
        { label: "RUP diumumkan", value: "8,6%", note: "Rp 1,05 T dari Rp 12,32 T — sisanya tertutup" },
        { label: "Yayasan terafiliasi parpol", value: "28 / 102", note: "Gerindra 7 · PKS 5 · PAN 4 · PDIP 3 · lainnya 9" },
        { label: "Terpidana korupsi pengurus", value: "3", note: "Total vonis 19 tahun · kerugian > Rp 145 M" },
      ],
      findings: [
        {
          n: "01",
          tag: "BUDGET HIJACKING",
          title: "Dana pendidikan Rp 223,55 T 'diculik' untuk makan siang",
          body: "Pemerintah mengalihkan dana Mandatory Spending pendidikan (20% APBN) untuk mendanai MBG. Digugat ke MK oleh koalisi masyarakat sipil karena dinilai melanggar UU APBN dan merugikan hak pendidikan murni.",
          source: "MK-RI · Kabariku",
        },
        {
          n: "02",
          tag: "OPASITAS PENGADAAN",
          title: "Baru 8,6% pengadaan diumumkan publik",
          body: "Dari total Rencana Umum Pengadaan Rp 12,32 T, hanya Rp 1,05 T yang terbit di SIRUP LKPP hingga April 2026. Sisanya tertutup atau via penunjukan langsung ke yayasan mitra.",
          source: "Katadata · LKPP",
        },
        {
          n: "03",
          tag: "PATRONASE POLITIK",
          title: "28 yayasan mitra terafiliasi partai — 7 di antaranya Gerindra",
          body: "ICW memetakan 28 dari 102 yayasan pelaksana SPPG terafiliasi partai politik. Termasuk Yayasan GSN (didirikan Prabowo, pengurus: Hashim Djojohadikusumo & Menhan Sjafrie Sjamsoeddin) dan Yasika (41 dapur di Sulsel — melampaui batas 10/provinsi).",
          source: "ICW · Tempo · Gelora",
        },
        {
          n: "04",
          tag: "INSIDER ↔ MITRA",
          title: "Tenaga Ahli BGN mendirikan yayasan mitra BGN sendiri",
          body: "I Dewa Made Agung Kertha (Tenaga Ahli BGN) mendirikan Yayasan IFSR — yang kemudian menjadi mitra SPPG program BGN. Alfatehan Septianta (Tim Teknis BGN) juga pengurus IFSR. Regulator dan yang diregulasi adalah orang yang sama.",
          source: "ICW Report",
        },
        {
          n: "05",
          tag: "TERPIDANA KORUPSI",
          title: "3 pengurus yayasan mitra adalah mantan napi korupsi",
          body: "Nur Alam (eks Gubernur Sultra, 12 tahun vonis, gratifikasi Rp 40,2 M) → Yayasan Lazuardi Kendari. Burhanuddin Abdullah (eks Gubernur BI, 5 tahun vonis, dana YLPPI Rp 100 M) → Yayasan IFSR, kini Komut PLN + Ketua Danantara. Abdul Hamid Payapo (eks PPK PUPR, korupsi Rp 5 M) → Yayasan Abdi Bangun Negeri.",
          source: "Tempo · ICW",
        },
      ],
      network: ["Prabowo Subianto", "Hashim Djojohadikusumo", "Menhan Sjafrie", "BGN", "Yayasan GSN", "YPPSDP", "28 yayasan mitra"],
    },
    {
      id: "bgn",
      code: "DOSSIER / 02",
      status: "ACTIVE",
      title: "Badan Gizi Nasional",
      subtitle: "Anomali Pengadaan & Revolving Door Peruri",
      kicker: "Kontrak Rp 600 M ke BUMN percetakan uang untuk sistem informasi kesehatan — penunjukan langsung. Markup tablet 80%. Satu CEO dua perusahaan Rp 700 M tanpa tender.",
      budget: "Rp 71 T",
      budgetNote: "Anggaran 2025 · pengadaan terdeteksi Rp 1,6 T",
      entities: 26,
      redFlags: 10,
      severity: "HIGH",
      sources: "BPK-RI · E-Purchasing LKPP · Tempo · ICW",
      keyFacts: [
        { label: "Kontrak Peruri tanpa tender", value: "Rp 600 M", note: "Sistem Informasi Gizi — via penunjukan langsung" },
        { label: "Markup tablet per unit", value: "Rp 7,95 jt", note: "Samsung Tab Active5 · total pagu Rp 508,4 M" },
        { label: "Markup sikat & semir sepatu", value: "~300%", note: "Rp 1,5 M untuk 'pendidikan SPPI'" },
        { label: "Double-dip satu CEO", value: "Rp 695 M", note: "PT IMI Rp 375 M + PT NSP Rp 320 M — pemilik sama" },
      ],
      findings: [
        {
          n: "01",
          tag: "MISMATCH KOMPETENSI",
          title: "BUMN cetak uang menang kontrak sistem kesehatan Rp 600 M",
          body: "BGN menunjuk langsung Perum Peruri (Percetakan Uang RI) untuk Sistem Informasi Gizi Nasional senilai Rp 600 M. Peruri mengalihkan ke anak perusahaan PT Peruri Digital Security (PDS, 99,78% saham Peruri).",
          source: "AHU · LPSE",
        },
        {
          n: "02",
          tag: "REVOLVING DOOR",
          title: "Komisaris Utama PDS adalah Chief DTO Kemenkes aktif",
          body: "Setiaji — Chief Digital Transformation Office Kementerian Kesehatan — menjabat sebagai Komisaris Utama PT Peruri Digital Security. Pejabat aktif regulator kesehatan mengawasi vendor yang menerima kontrak dari regulator lain (BGN). Wakil Dirut PDS, Rahmat Danu Andika, sebelumnya Direktur GovTech Procurement Telkom.",
          source: "PDS.co.id · Tempo",
        },
        {
          n: "03",
          tag: "MARKUP HARDWARE",
          title: "Tablet Samsung di e-Katalog Rp 17,93 jt vs pasar Rp 9–12 jt",
          body: "Pengadaan 1 perangkat Samsung Galaxy Tab Active5 untuk program SPPI senilai Rp 508,4 M. Analisis ICW menemukan markup Rp 7,95 jt per unit. Vendor utama: PT Mitrawira Hutama Teknologi.",
          source: "ICW · Jawa Pos · Pikiran Rakyat",
        },
        {
          n: "04",
          tag: "PEMBOROSAN",
          title: "Rp 1,5 M untuk sikat dan semir sepatu — markup 300%",
          body: "12 paket kontrak e-Purchasing untuk sikat & semir sepatu (merek Kiwi) senilai total Rp 1,57 M. Harga Inaproc Rp 50–56 rb/unit, harga pasar Rp 18–19 rb. Kategorikan 'pendukung pendidikan SPPI'. Vendor: PT Gajah Mitra Paragon (Bandung).",
          source: "Tempo · Fin.co.id",
        },
        {
          n: "05",
          tag: "BENEFICIAL OWNER",
          title: "Satu CEO, dua perusahaan, dua kontrak — total Rp 695 M",
          body: "Shoraya Lolyta Oktaviana tercatat sebagai pemilik manfaat PT Indoraya Multi Internasional (IMI, Rp 375 M) dan PT Nagatama Septa Persada (NSP, Rp 320 M) — keduanya menang kontrak rak koperasi Agrinas. Terafiliasi dengan Nanik S. Deyang (Wakil Kepala BGN). Diduga menggunakan NIK ganda.",
          source: "AHU · Investigasi internal",
        },
      ],
      network: ["BGN", "Peruri", "PDS", "Setiaji (Kemenkes)", "PT IMI", "PT NSP", "Shoraya Lolyta"],
    },
    {
      id: "kmp",
      code: "DOSSIER / 03",
      status: "VERIFIED",
      title: "Koperasi Merah Putih",
      subtitle: "Gurita Agrinas & Monopoli Infrastruktur Desa",
      kicker: "80.081 gerai koperasi desa, Rp 128 T, tanpa tender. Kontraktor utama dikuasai yayasan presiden. Pendanaan dari Danantara yang dipimpin eks-napi korupsi.",
      budget: "Rp 210–216 T",
      budgetNote: "Rp 128 T konstruksi · Rp 10,83 T logistik · Rp 24,66 T impor",
      entities: 17,
      redFlags: 11,
      severity: "HIGH",
      sources: "Tempo Investigasi · The Gecko Project · CELIOS · CNN",
      keyFacts: [
        { label: "Unit gerai target", value: "80.081", note: "Rp 2,5 M capex + Rp 500 jt opex per unit" },
        { label: "Kontrak Agrinas", value: "Rp 128 T", note: "Penugasan langsung via Inpres 9/2025" },
        { label: "Markup per gerai (Denpasar)", value: "Rp 700 jt", note: "Pagu Rp 1,6 M · fisik riil Rp 800–900 jt" },
        { label: "Potensi korupsi (CELIOS)", value: "Rp 4,8 T", note: "Studi 108 kepala desa · 34 provinsi" },
      ],
      findings: [
        {
          n: "01",
          tag: "STATE CAPTURE",
          title: "Presiden kontrak ke yayasan yang ia pimpin sendiri",
          body: "Prabowo Subianto adalah Ketua Pembina YPPSDP — yayasan Kemenhan yang memegang 99% saham PT Agrinas. Agrinas ditunjuk sebagai kontraktor utama KMP via Inpres 9/2025 yang ditandatangani Prabowo. Pembuat kebijakan = pengendali kontraktor.",
          source: "Tempo Investigasi 164314",
        },
        {
          n: "02",
          tag: "MARKUP TERBUKTI",
          title: "Gerai Denpasar: pagu Rp 1,6 M, fisik riil Rp 800–900 jt",
          body: "Investigasi lapangan Rubic News di Terminal Tegal, Denpasar menemukan selisih ~Rp 700 jt per unit. Jika konsisten nasional × 80.081 unit = potensi markup Rp 56 T.",
          source: "Rubic News · Bali Politika",
        },
        {
          n: "03",
          tag: "REVOLVING DOOR",
          title: "Direktur Agrinas → Asisten Khusus Presiden",
          body: "Dirgayuza Setyawan: Kepala Divisi Medsos Gerindra → Direktur Operasi Agrinas → Asisten Khusus Presiden Prabowo (Oktober 2025). Orang yang tahu seluruh operasi internal kontraktor kini di lingkaran inti istana.",
          source: "Tempo Profil 2077755",
        },
        {
          n: "04",
          tag: "LOOP TERTUTUP",
          title: "Danantara danai KMP — dipimpin mantan terpidana korupsi",
          body: "Danantara mengalokasikan Rp 210–216 T untuk KMP via bank Himbara. Ketua Tim Pakar Danantara: Burhanuddin Abdullah — eks Gubernur BI yang divonis 5 tahun (2008) untuk penyalahgunaan dana YLPPI Rp 100 M. Agustus 2025 menerima Bintang Mahaputera dari Prabowo.",
          source: "VOI · Liputan6 · Kompas",
        },
        {
          n: "05",
          tag: "SUPER NODE",
          title: "YPPSDP: satu yayasan, tiga saluran anggaran negara",
          body: "YPPSDP mengendalikan: (1) Agrinas — konstruksi KMP Rp 128 T+, (2) PT TMI — intermediary alutsista (draft Perpres USD 124,99 miliar), (3) Yayasan mitra SPPG MBG. Direksi TMI hampir seluruhnya teman seangkatan Prabowo di AKABRI 1970 atau kader Gerindra. PBHI+ICW+Imparsial sudah laporkan ke Ombudsman (Feb 2024).",
          source: "Kompas · PBHI · Majalah Tempo",
        },
        {
          n: "06",
          tag: "INTEGRASI VERTIKAL",
          title: "199 KMP sudah jadi supplier SPPG MBG",
          body: "Agrinas akan mengontrol: konstruksi dapur MBG (SPPG), distribusi bahan pangan (KMP), logistik (motor listrik BGN + impor 105.000 kendaraan India). Satu ekosistem di bawah kendali yayasan presiden menguasai seluruh rantai pangan program sosial Rp 71 T+.",
          source: "Kompas Money · Jakarta Post",
        },
      ],
      network: ["Prabowo Subianto", "YPPSDP", "Agrinas", "PT TMI", "Danantara", "Burhanuddin Abdullah", "PMJS", "Gerai KMP"],
    },
  ],

  actors: [
    { name: "Prabowo Subianto", role: "Presiden RI · Ketua Pembina YPPSDP", flags: ["KMP", "MBG"], severity: "HIGH", note: "Pembuat Inpres 9/2025 sekaligus pengendali kontraktor utama" },
    { name: "Burhanuddin Abdullah", role: "Ketua Danantara · Komut PLN · eks Gubernur BI", flags: ["MBG", "KMP"], severity: "HIGH", note: "Vonis 5 tahun korupsi YLPPI Rp 100 M (2008). Pengawas Yayasan IFSR mitra BGN" },
    { name: "Sjafrie Sjamsoeddin", role: "Menteri Pertahanan · Ketua Pembina YPPSDP", flags: ["KMP"], severity: "HIGH", note: "Mengawasi yayasan pengendali Agrinas & broker alutsista TMI" },
    { name: "Musa Bangun", role: "Waketum Gerindra · Komut Inalum · Ketua YPPSDP", flags: ["KMP"], severity: "HIGH", note: "Triple akses: partai · BUMN tambang · yayasan Kemenhan" },
    { name: "Dirgayuza Setyawan", role: "Asisten Khusus Presiden · eks Direktur Agrinas", flags: ["KMP"], severity: "HIGH", note: "Revolving door Gerindra → Agrinas → Istana" },
    { name: "Angga Raka Prabowo", role: "Kepala BKP · Komut Telkom · eks Komisaris TMI", flags: ["KMP"], severity: "HIGH", note: "Loyalis Prabowo 17 tahun. Multi-revolving door." },
    { name: "Glenny H. Kairupan", role: "Dirut Garuda Indonesia · eks Komut TMI", flags: ["KMP"], severity: "MED", note: "AKABRI 1970 — seangkatan Prabowo" },
    { name: "Setiaji", role: "Chief DTO Kemenkes · Komut PDS", flags: ["BGN"], severity: "HIGH", note: "Pejabat aktif Kemenkes mengawasi BUMN penerima kontrak Rp 600 M" },
    { name: "Nur Alam", role: "Pendiri Yayasan Lazuardi · eks Gubernur Sultra", flags: ["MBG"], severity: "HIGH", note: "Terpidana 12 tahun · gratifikasi Rp 40,2 M · kerusakan lingkungan US$ 4 M" },
    { name: "I Dewa Made A. Kertha", role: "Tenaga Ahli BGN · Pendiri Yayasan IFSR", flags: ["MBG"], severity: "HIGH", note: "Insider regulator mendirikan mitra regulator" },
    { name: "Shoraya L. Oktaviana", role: "CEO PT IMI & PT NSP", flags: ["BGN", "KMP"], severity: "HIGH", note: "Beneficial owner ganda · kontrak total Rp 695 M · dugaan NIK ganda" },
    { name: "Ferry Juliantono", role: "Menteri Koperasi · Waketum Gerindra", flags: ["KMP"], severity: "MED", note: "Menteri kader Gerindra mengawasi program yang dikontrol yayasan Prabowo" },
  ],

  timeline: [
    { date: "2024 · Ags", event: "PT TMI didirikan — 99,8% milik YPPSDP. Broker alutsista draft Perpres USD 124,99 miliar." },
    { date: "2024 · Okt", event: "Perpres 83/2024: Badan Gizi Nasional dibentuk. Anggaran awal Rp 71 T." },
    { date: "2024 · Nov", event: "Surat Prabowo ke CEO Rosoboronexport memperkenalkan TMI sebagai intermediary alutsista." },
    { date: "2025 · Jan", event: "MBG resmi operasional nasional. Distribusi via SPPG." },
    { date: "2025 · Feb", event: "Danantara diluncurkan. Burhanuddin Abdullah → Ketua Tim Pakar. Kelola USD 900 M aset BUMN." },
    { date: "2025 · Jul", event: "Inpres 9/2025 — KMP resmi. 80.081 target unit. Agrinas kontraktor utama tanpa tender." },
    { date: "2025 · Agu", event: "Prabowo beri Bintang Mahaputera Adipradana ke Burhanuddin Abdullah." },
    { date: "2025 · Sep", event: "Angga Raka Prabowo → Kepala Badan Komunikasi Pemerintah." },
    { date: "2025 · Okt", event: "Dirgayuza Setyawan → Asisten Khusus Presiden. Glenny Kairupan → Dirut Garuda." },
    { date: "2026 · Jan", event: "ICW rilis 'Ada Siapa di Balik MBG': 28 yayasan parpol, 3 eks napi korupsi." },
    { date: "2026 · Feb", event: "Kontrak impor 105.000 pikap India (Mahindra+Tata) Rp 24,66 T ke Agrinas. DP 30% dibayar." },
    { date: "2026 · Mar", event: "Gugatan MK: Dana Pendidikan Rp 223,55 T dialihkan ke MBG — dinilai inkonstitusional." },
    { date: "2026 · Apr", event: "Investigasi lapangan Denpasar: gerai KMP fisik Rp 800 jt, pagu Rp 1,6 M. Potensi markup nasional Rp 56 T." },
  ],
};
