import { isCaseStudy, type CaseStudy, type CaseStudyMetadata } from "@/types/graph";

// Merge multiple validated CaseStudy objects into one.
// Entities and red_flags are deduplicated by id; relations are concatenated as-is.
// Metadata is derived from all sources: latest date, combined sumber, fixed status.
function mergeCaseStudies(studies: readonly CaseStudy[]): CaseStudy {
  const seenEntityIds = new Set<string>();
  const seenRedFlagIds = new Set<string>();

  const entities = studies.flatMap((s) =>
    s.entities.filter((e) => {
      if (seenEntityIds.has(e.id)) return false;
      seenEntityIds.add(e.id);
      return true;
    })
  );

  const relations = Array.from(
    new Map(
      studies
        .flatMap((s) => s.relations)
        .map((r) => [`${r.from}-${r.type}-${r.to}`, r])
    ).values()
  );

  const red_flags = studies.flatMap((s) =>
    s.red_flags.filter((rf) => {
      if (seenRedFlagIds.has(rf.id)) return false;
      seenRedFlagIds.add(rf.id);
      return true;
    })
  );

  const investigasi_lanjutan = studies.flatMap((s) => s.investigasi_lanjutan);

  // Latest date wins and sources are joined.
  const latestDate = studies
    .map((s) => s.metadata.tanggal_riset)
    .sort()
    .at(-1) ?? "";

  const combinedSumber = studies
    .map((s) => s.metadata.sumber)
    .join("; ");

  const metadata: CaseStudyMetadata = {
    tanggal_riset: latestDate,
    sumber: combinedSumber,
    status: "Data Publik Tersusun",
  };

  return { metadata, entities, relations, red_flags, investigasi_lanjutan };
}

// Shared data loader reads and merges all case study JSON files from public/data/.
// Called server-side only; never imported in client components.
export async function getCaseStudy(onlyFeatured = false): Promise<CaseStudy | null> {
  try {
    const { readFile, readdir } = await import("fs/promises");
    const { join } = await import("path");

    const dataDir = join(process.cwd(), "public", "data");
    const allFiles = await readdir(dataDir);
    const caseStudyFiles = allFiles.filter(f => f.startsWith("case_study_") && f.endsWith(".json"));

    const studies: CaseStudy[] = [];

    for (const filename of caseStudyFiles) {
      const filePath = join(dataDir, filename);
      const raw = await readFile(filePath, "utf-8");
      const data: unknown = JSON.parse(raw);

      if (!isCaseStudy(data)) {
        console.error(`Data JSON tidak valid: ${filename} tidak sesuai skema.`);
        continue;
      }

      studies.push(data);
    }

    if (studies.length === 0) {
      console.error("Tidak ada file data yang valid.");
      return null;
    }

    return mergeCaseStudies(studies);
  } catch (err) {
    console.error("Gagal memuat data:", err);
    return null;
  }
}

/**
 * Calculates aggregate stats from all available case studies and the
 * pre-computed SPPG summary file.
 *
 * SPPG totals come from `frontend/public/data/sppg_summary.json`, which is a
 * tiny file generated by `etl/generate_sppg_summary.py` from the much larger
 * `all_sppg_locations.json`. We read it as plain JSON — no stream parsing,
 * no regex — so adding fields to the source file can't break the frontend.
 */
export async function getLiveStats() {
  const fullData = await getCaseStudy(true);
  if (!fullData) return null;

  const { readFile } = await import("fs/promises");
  const { join } = await import("path");

  let totalSppg = 0;
  let totalSuspended = 0;
  let certificationRate = "0%";
  let mappedSppg = 0;

  try {
    const summaryPath = join(process.cwd(), "public", "data", "sppg_summary.json");
    const summary = JSON.parse(await readFile(summaryPath, "utf-8")) as {
      total_official?: number;
      total_suspended?: number;
      certification_rate?: string;
    };
    totalSppg = summary.total_official ?? 0;
    totalSuspended = summary.total_suspended ?? 0;
    certificationRate = summary.certification_rate ?? "0%";
  } catch (err) {
    console.error("Gagal memuat sppg_summary.json:", err);
  }

  try {
    const pointsPath = join(process.cwd(), "public", "data", "sppg_points.json");
    const pointsData = JSON.parse(await readFile(pointsPath, "utf-8")) as unknown[];
    mappedSppg = Array.isArray(pointsData) ? pointsData.length : 0;
  } catch (err) {
    console.error("Gagal memuat sppg_points.json:", err);
  }

  return {
    TOTAL_ENTITIES: fullData.entities.length,
    TOTAL_RELATIONS: fullData.relations.length,
    TOTAL_RED_FLAGS: fullData.red_flags.length,
    TOTAL_SPPG: totalSppg,
    TOTAL_SUSPENDED: totalSuspended,
    CERTIFICATION_RATE: certificationRate,
    MAPPED_SPPG: mappedSppg,
    LATEST_UPDATE: fullData.metadata.tanggal_riset || new Date().toISOString().split("T")[0],
  };
}
