import { isCaseStudy, type CaseStudy, type CaseStudyMetadata } from "@/types/graph";

// Merge multiple validated CaseStudy objects into one.
// Entities and red_flags are deduplicated by id; relations are concatenated as-is.
// Metadata is derived from all sources: latest date, combined sumber, fixed status.
function mergeCaseStudies(studies: readonly CaseStudy[]): CaseStudy {
  const seenEntityIds = new Set<string>();
  const seenRedFlagIds = new Set<string>();

  const entities = studies.flatMap((s) =>
    s.entities.filter((e) => {
      if (seenEntityIds.has(e.id)) return false;
      seenEntityIds.add(e.id);
      return true;
    })
  );

  const relations = Array.from(
    new Map(
      studies
        .flatMap((s) => s.relations)
        .map((r) => [`${r.from}-${r.type}-${r.to}`, r])
    ).values()
  );

  const red_flags = studies.flatMap((s) =>
    s.red_flags.filter((rf) => {
      if (seenRedFlagIds.has(rf.id)) return false;
      seenRedFlagIds.add(rf.id);
      return true;
    })
  );

  const investigasi_lanjutan = studies.flatMap((s) => s.investigasi_lanjutan);

  // Latest date wins and sources are joined.
  const latestDate = studies
    .map((s) => s.metadata.tanggal_riset)
    .sort()
    .at(-1) ?? "";

  const combinedSumber = studies
    .map((s) => s.metadata.sumber)
    .join("; ");

  const metadata: CaseStudyMetadata = {
    tanggal_riset: latestDate,
    sumber: combinedSumber,
    status: "Data Publik Tersusun",
  };

  return { metadata, entities, relations, red_flags, investigasi_lanjutan };
}

// Shared data loader reads and merges all case study JSON files from public/data/.
// Called server-side only; never imported in client components.
export async function getCaseStudy(onlyFeatured = false): Promise<CaseStudy | null> {
  try {
    const { readFile, readdir } = await import("fs/promises");
    const { join } = await import("path");

    const dataDir = join(process.cwd(), "public", "data");
    const allFiles = await readdir(dataDir);
    const caseStudyFiles = allFiles.filter(f => f.startsWith("case_study_") && f.endsWith(".json"));

    const studies: CaseStudy[] = [];

    for (const filename of caseStudyFiles) {
      const filePath = join(dataDir, filename);
      const raw = await readFile(filePath, "utf-8");
      const data: unknown = JSON.parse(raw);

      if (!isCaseStudy(data)) {
        console.error(`Data JSON tidak valid: ${filename} tidak sesuai skema.`);
        continue;
      }

      studies.push(data);
    }

    if (studies.length === 0) {
      console.error("Tidak ada file data yang valid.");
      return null;
    }

    return mergeCaseStudies(studies);
  } catch (err) {
    console.error("Gagal memuat data:", err);
    return null;
  }
}

/**
 * Shape of frontend/public/data/metadata_summary.json.
 * Generated by etl/generate_metadata_summary.py — keep in sync with that script.
 */
interface MetadataSummary {
  readonly generated_at: string;
  readonly stats: {
    readonly total_sppg: number;
    readonly total_suspended: number;
    readonly certification_rate: string;
    readonly mapped_sppg: number;
  };
}

async function readMetadataSummary(): Promise<MetadataSummary["stats"] | null> {
  try {
    const { readFile } = await import("fs/promises");
    const { join } = await import("path");
    const path = join(process.cwd(), "public", "data", "metadata_summary.json");
    const raw = await readFile(path, "utf-8");
    const parsed = JSON.parse(raw) as MetadataSummary;
    return parsed?.stats ?? null;
  } catch (err) {
    console.error("Gagal memuat metadata_summary.json:", err);
    return null;
  }
}

/**
 * Calculates aggregate stats from the case studies and the prebuilt
 * SPPG metadata summary. The summary file is generated by
 * `etl/generate_metadata_summary.py` and is tiny (< 1 KB), so reading it on
 * every server render is cheap.
 */
export async function getLiveStats() {
  const fullData = await getCaseStudy(true);
  if (!fullData) return null;

  const summary = await readMetadataSummary();

  return {
    TOTAL_ENTITIES: fullData.entities.length,
    TOTAL_RELATIONS: fullData.relations.length,
    TOTAL_RED_FLAGS: fullData.red_flags.length,
    TOTAL_SPPG: summary?.total_sppg ?? 0,
    TOTAL_SUSPENDED: summary?.total_suspended ?? 0,
    CERTIFICATION_RATE: summary?.certification_rate ?? "0%",
    MAPPED_SPPG: summary?.mapped_sppg ?? 0,
    LATEST_UPDATE: fullData.metadata.tanggal_riset || new Date().toISOString().split("T")[0],
  };
}
